version: "3.3"

services:
  postgresql:
    networks:
      default:
    image: ${POSTGRESQL_IMAGE}
    restart: always
    env_file:
      - ${env_files}/postgresql.env
    secrets:
      - postgres_password
    volumes:
      - ${volumes}/postgresql/var/lib/postgresql/data:/var/lib/postgresql/data
      - ${volumes}/postgresql/etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf

  gitlab:
    networks:
      default:
      traefik:
    image: ${GITLAB_IMAGE}
    restart: always
    depends_on:
      - postgresql
    environment:
      - EXTERNAL_SCHEME=${GITLAB_EXTERNAL_SCHEME}
      - EXTERNAL_DOMAIN=${GITLAB_EXTERNAL_DOMAIN}
      - REGISTRY_EXTERNAL_DOMAIN=${GITLAB_REGISTRY_EXTERNAL_DOMAIN}
      - MATTERMOST_EXTERNAL_DOMAIN=${GITLAB_MATTERMOST_EXTERNAL_DOMAIN}
      - PAGES_EXTERNAL_DOMAIN=${GITLAB_PAGES_EXTERNAL_DOMAIN}
    env_file:
      - ${env_files}/gitlab.env
    secrets:
      - gitlab_auth_token
      - gitlab_root_password
      - postgres_password
    volumes:
      # config file
      - ${configs}/gitlab/gitlab.rb:/gitlab.rb
      #
      - ${volumes}/gitlab/etc/gitlab:/etc/gitlab
      - ${volumes}/gitlab/var/log/gitlab:/var/log/gitlab
      - ${volumes}/gitlab/var/opt/gitlab:/var/opt/gitlab
    labels:
      - "traefik.enable=true"

      # Web Interface
      - "traefik.http.routers.http_gitlab.rule=Host(`${GITLAB_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.http_gitlab.entrypoints=web"
      - "traefik.http.routers.http_gitlab.middlewares=defaultchain@file,redirectToHttps@file"

      - "traefik.http.routers.https_gitlab.rule=Host(`${GITLAB_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.https_gitlab.entrypoints=websecure"
      - "traefik.http.routers.https_gitlab.middlewares=defaultchain@file"
      - "traefik.http.routers.https_gitlab.service=gitlab"
      - "traefik.http.routers.https_gitlab.tls=true"
      - "traefik.http.routers.https_gitlab.tls.certresolver=hetzner01"
      - "traefik.http.routers.https_gitxlab.tls.domains[0].main=${GITLAB_EXTERNAL_DOMAIN}"
      
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      - "traefik.http.services.gitlab.loadbalancer.server.scheme=http"
      # - "traefik.http.services.gitlab.loadbalancer.healthcheck.interval=10s"
      # - "traefik.http.services.gitlab.loadbalancer.healthcheck.port=80"
      # - "traefik.http.services.gitlab.loadbalancer.healthcheck.scheme=http"
      # - "traefik.http.services.gitlab.loadbalancer.healthcheck.path=-/-/readiness"
      - "traefik.http.services.gitlab.loadbalancer.sticky.cookie=true"

networks:
  traefik:
    external:
      name: traefik_bridge

secrets:
  gitlab_auth_token:
    file: ${secrets}/gitlab_auth_token.txt
  gitlab_root_password:
    file: ${secrets}/gitlab_root_password.txt
  postgres_password:
    file: ${secrets}/postgres_password.txt
