version: "3.3"

services:
  gitlab:
    networks:
      default:
      traefik:
    image: ${GITLAB_IMAGE}
    restart: always
    environment:
      - EXTERNAL_SCHEME=${GITLAB_EXTERNAL_SCHEME}
      - REGISTRY_EXTERNAL_SCHEME=${GITLAB_REGISTRY_EXTERNAL_SCHEME}
      - MATTERMOST_EXTERNAL_SCHEME=${GITLAB_MATTERMOST_EXTERNAL_SCHEME}
      - PAGES_EXTERNAL_SCHEME=${GITLAB_PAGES_EXTERNAL_SCHEME}

      - EXTERNAL_DOMAIN=${GITLAB_EXTERNAL_DOMAIN}
      - REGISTRY_EXTERNAL_DOMAIN=${GITLAB_REGISTRY_EXTERNAL_DOMAIN}
      - MATTERMOST_EXTERNAL_DOMAIN=${GITLAB_MATTERMOST_EXTERNAL_DOMAIN}
      - PAGES_EXTERNAL_DOMAIN=${GITLAB_PAGES_EXTERNAL_DOMAIN}

      - EXTERNAL_PORT=${GITLAB_EXTERNAL_PORT}
      - REGISTRY_EXTERNAL_PORT=${GITLAB_REGISTRY_EXTERNAL_PORT}
      - MATTERMOST_EXTERNAL_PORT=${GITLAB_MATTERMOST_EXTERNAL_PORT}
      - PAGES_EXTERNAL_PORT=${GITLAB_PAGES_EXTERNAL_PORT}
    env_file:
      - ${env_files}/gitlab.env
    secrets:
      - gitlab_auth_token
      - gitlab_root_password
      - gitlab_smtp_password
      - gitlab_smtp_user
    volumes:
      # config file
      - ${configs}/gitlab/gitlab.rb:/gitlab.rb
      #
      - ${volumes}/gitlab/etc/gitlab:/etc/gitlab
      - ${volumes}/gitlab/var/log/gitlab:/var/log/gitlab
      - ${volumes}/gitlab/var/opt/gitlab:/var/opt/gitlab
    ports:
      - ${GITLAB_EXTERNAL_PORT}:${GITLAB_EXTERNAL_PORT}
      - ${GITLAB_REGISTRY_EXTERNAL_PORT}:${GITLAB_REGISTRY_EXTERNAL_PORT}
      - ${GITLAB_MATTERMOST_EXTERNAL_PORT}:${GITLAB_MATTERMOST_EXTERNAL_PORT}
      - ${GITLAB_PAGES_EXTERNAL_PORT}:${GITLAB_PAGES_EXTERNAL_PORT}
    labels:
      - "traefik.enable=true"

      # Web Interface
      - "traefik.http.routers.http_gitlab_web.rule=Host(`${GITLAB_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.http_gitlab_web.entrypoints=web"
      - "traefik.http.routers.http_gitlab_web.middlewares=defaultchain@file,redirectToHttps@file"
      - "traefik.http.routers.https_gitlab_web.rule=Host(`${GITLAB_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.https_gitlab_web.entrypoints=websecure"
      - "traefik.http.routers.https_gitlab_web.middlewares=defaultchain@file"
      - "traefik.http.routers.https_gitlab_web.service=gitlab_web"
      - "traefik.http.routers.https_gitlab_web.tls=true"
      - "traefik.http.routers.https_gitlab_web.tls.certresolver=hetzner01"
      - "traefik.http.routers.https_gitlab_web.tls.domains[0].main=${GITLAB_EXTERNAL_DOMAIN}"
      - "traefik.http.services.gitlab_web.loadbalancer.server.port=${GITLAB_EXTERNAL_PORT}"
      - "traefik.http.services.gitlab_web.loadbalancer.server.scheme=http"
      - "traefik.http.services.gitlab_web.loadbalancer.sticky.cookie=true"

      - "traefik.http.routers.http_gitlab_registry.rule=Host(`${GITLAB_REGISTRY_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.http_gitlab_registry.entrypoints=web"
      - "traefik.http.routers.http_gitlab_registry.middlewares=defaultchain@file,redirectToHttps@file"
      - "traefik.http.routers.https_gitlab_registry.rule=Host(`${GITLAB_REGISTRY_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.https_gitlab_registry.entrypoints=websecure"
      - "traefik.http.routers.https_gitlab_registry.middlewares=defaultchain@file"
      - "traefik.http.routers.https_gitlab_registry.service=gitlab_registry"
      - "traefik.http.routers.https_gitlab_registry.tls=true"
      - "traefik.http.routers.https_gitlab_registry.tls.certresolver=hetzner01"
      - "traefik.http.routers.https_gitlab_registry.tls.domains[0].main=$GITLAB_REGISTRY_EXTERNAL_DOMAIN}"
      - "traefik.http.services.gitlab_registry.loadbalancer.server.port=${GITLAB_REGISTRY_EXTERNAL_PORT}"
      - "traefik.http.services.gitlab_registry.loadbalancer.server.scheme=http"
      - "traefik.http.services.gitlab_registry.loadbalancer.sticky.cookie=true"

      - "traefik.http.routers.http_gitlab_mattermost.rule=Host(`${GITLAB_MATTERMOST_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.http_gitlab_mattermost.entrypoints=web"
      - "traefik.http.routers.http_gitlab_mattermost.middlewares=defaultchain@file,redirectToHttps@file"
      - "traefik.http.routers.https_gitlab_mattermost.rule=Host(`${GITLAB_MATTERMOST_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.https_gitlab_mattermost.entrypoints=websecure"
      - "traefik.http.routers.https_gitlab_mattermost.middlewares=defaultchain@file"
      - "traefik.http.routers.https_gitlab_mattermost.service=gitlab_mattermost"
      - "traefik.http.routers.https_gitlab_mattermost.tls=true"
      - "traefik.http.routers.https_gitlab_mattermost.tls.certresolver=hetzner01"
      - "traefik.http.routers.https_gitlab_mattermost.tls.domains[0].main=${GITLAB_MATTERMOST_EXTERNAL_DOMAIN}"
      - "traefik.http.services.gitlab_mattermost.loadbalancer.server.port=${GITLAB_MATTERMOST_EXTERNAL_PORT}"
      - "traefik.http.services.gitlab_mattermost.loadbalancer.server.scheme=http"
      - "traefik.http.services.gitlab_mattermost.loadbalancer.sticky.cookie=true"

      - "traefik.http.routers.http_gitlab_pages.rule=HostRegexp(`${GITLAB_PAGES_EXTERNAL_DOMAIN}`, `{subdomain:[a-z]+}.${GITLAB_PAGES_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.http_gitlab_pages.entrypoints=web"
      - "traefik.http.routers.http_gitlab_pages.middlewares=defaultchain@file,redirectToHttps@file"
      - "traefik.http.routers.https_gitlab_pages.rule=HostRegexp(`${GITLAB_PAGES_EXTERNAL_DOMAIN}`, `{subdomain:[a-z]+}.${GITLAB_PAGES_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.https_gitlab_pages.entrypoints=websecure"
      # - "traefik.http.routers.https_gitlab_pages.middlewares=defaultchain@file"
      - "traefik.http.routers.https_gitlab_pages.service=gitlab_pages"
      - "traefik.http.routers.https_gitlab_pages.tls=true"
      - "traefik.http.routers.https_gitlab_pages.tls.certresolver=hetzner01"
      - "traefik.http.routers.https_gitlab_pages.tls.domains[0].main=${GITLAB_PAGES_EXTERNAL_DOMAIN}"
      - "traefik.http.routers.https_gitlab_pages.tls.domains[1].main=*.${GITLAB_PAGES_EXTERNAL_DOMAIN}"
      - "traefik.http.services.gitlab_pages.loadbalancer.server.port=${GITLAB_PAGES_EXTERNAL_PORT}"
      - "traefik.http.services.gitlab_pages.loadbalancer.server.scheme=http"
      - "traefik.http.services.gitlab_pages.loadbalancer.sticky.cookie=true"

  runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    networks:
      default:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${volumes}/runner/etc/gitlab-runner:/etc/gitlab-runner

networks:
  traefik:
    external:
      name: traefik_bridge

secrets:
  gitlab_auth_token:
    file: ${secrets}/gitlab_auth_token.txt
  gitlab_root_password:
    file: ${secrets}/gitlab_root_password.txt
  gitlab_smtp_password:
    file: ${secrets}/gitlab_smtp_password.txt
  gitlab_smtp_user:
    file: ${secrets}/gitlab_smtp_user.txt