##! You can run `gitlab-ctl diff-config` to compare the contents of the current gitlab.rb with
##! the gitlab.rb.template from the currently running version.

##! You can run `gitlab-ctl show-config` to display the configuration that will be generated by
##! running `gitlab-ctl reconfigure`

################################################################################
################################################################################
##                Configuration Settings for GitLab CE and EE                 ##
################################################################################
################################################################################

################################################################################
## gitlab.yml configuration
##! Docs: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/gitlab.yml.md
################################################################################

external_url ENV['EXTERNAL_SCHEME'] + "://" + ENV['EXTERNAL_DOMAIN']

## SSH
gitlab_rails['gitlab_ssh_host'] = ENV['EXTERNAL_DOMAIN']
gitlab_rails['gitlab_ssh_user'] = 'git'
gitlab_rails['time_zone'] = 'UTC'

### GitLab email server settings
###! Docs: https://docs.gitlab.com/omnibus/settings/smtp.html
###! **Use smtp instead of sendmail/postfix.**
gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = ENV['SMTP_HOST']
gitlab_rails['smtp_port'] = ENV['SMTP_PORT']
gitlab_rails['smtp_user_name'] = File.read('/run/secrets/gitlab_smtp_user')
gitlab_rails['smtp_password'] = File.read('/run/secrets/gitlab_smtp_password')
gitlab_rails['smtp_domain'] = ENV['SMTP_HOST']
gitlab_rails['smtp_authentication'] = "login"
gitlab_rails['smtp_enable_starttls_auto'] = true
gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
gitlab_rails['gitlab_email_from'] = 'me@' + ENV['EXTERNAL_DOMAIN']
gitlab_rails['gitlab_email_reply_to'] = 'noreply@' + ENV['EXTERNAL_DOMAIN']

## GitLab user privileges
gitlab_rails['gitlab_default_can_create_group'] = true
gitlab_rails['gitlab_username_changing_enabled'] = true

## Default Theme
gitlab_rails['gitlab_default_theme'] = 2

## Default project feature settings
gitlab_rails['gitlab_default_projects_features_issues'] = true
gitlab_rails['gitlab_default_projects_features_merge_requests'] = true
gitlab_rails['gitlab_default_projects_features_wiki'] = true
gitlab_rails['gitlab_default_projects_features_snippets'] = true
gitlab_rails['gitlab_default_projects_features_builds'] = true
gitlab_rails['gitlab_default_projects_features_container_registry'] = true

## Reply by email
##! Allow users to comment on issues and merge requests by replying to
##! notification emails.
##! Docs: https://docs.gitlab.com/ee/administration/reply_by_email.html
gitlab_rails['incoming_email_enabled'] = true

### Incoming Email Address
gitlab_rails['incoming_email_address'] = "incoming+%{key}@" + ENV['EXTERNAL_DOMAIN']

### Email account username
gitlab_rails['incoming_email_email'] = File.read('/run/secrets/gitlab_imap_user')

### Email account password
gitlab_rails['incoming_email_password'] = File.read('/run/secrets/gitlab_imap_password')

### IMAP Settings
gitlab_rails['incoming_email_host'] = ENV['IMAP_HOST']
gitlab_rails['incoming_email_port'] = ENV['IMAP_PORT']
gitlab_rails['incoming_email_ssl'] = false
gitlab_rails['incoming_email_start_tls'] = true

### Incoming Mailbox Settings (via `mail_room`)
###! The mailbox where incoming mail will end up. Usually "inbox".
gitlab_rails['incoming_email_mailbox_name'] = "inbox"
###! The IDLE command timeout.
gitlab_rails['incoming_email_idle_timeout'] = 60
###! The file name for internal `mail_room` JSON logfile
gitlab_rails['incoming_email_log_file'] = "/var/log/gitlab/mailroom/mail_room_json.log"
###! Permanently remove messages from the mailbox when they are deleted after delivery
gitlab_rails['incoming_email_expunge_deleted'] = true

###! The format of mail_room crash logs
mailroom['exit_log_format'] = "plain"

## Job Artifacts
gitlab_rails['artifacts_enabled'] = true
gitlab_rails['artifacts_path'] = "/var/opt/gitlab/gitlab-rails/shared/artifacts"

## External merge request diffs
gitlab_rails['external_diffs_enabled'] = false
gitlab_rails['external_diffs_when'] = nil
gitlab_rails['external_diffs_storage_path'] = "/var/opt/gitlab/gitlab-rails/shared/external-diffs"

## Git LFS
gitlab_rails['lfs_enabled'] = true
gitlab_rails['lfs_storage_path'] = "/var/opt/gitlab/gitlab-rails/shared/lfs-objects"

## GitLab uploads
##! Docs: https://docs.gitlab.com/ee/administration/uploads.html
gitlab_rails['uploads_directory'] = "/var/opt/gitlab/gitlab-rails/uploads"
gitlab_rails['uploads_storage_path'] = "/opt/gitlab/embedded/service/gitlab-rails/public"
gitlab_rails['uploads_base_dir'] = "uploads/-/system"

## Terraform state
##! Docs: https://docs.gitlab.com/ee/administration/terraform_state
gitlab_rails['terraform_state_enabled'] = true
gitlab_rails['terraform_state_storage_path'] = "/var/opt/gitlab/gitlab-rails/shared/terraform_state"

## Impersonation settings
gitlab_rails['impersonation_enabled'] = true

## Backup Settings
##! Docs: https://docs.gitlab.com/omnibus/settings/backups.html

gitlab_rails['manage_backup_path'] = true
gitlab_rails['backup_path'] = "/var/opt/gitlab/backups"

##! Docs: https://docs.gitlab.com/ee/raketasks/backup_restore.html#backup-archive-permissions
gitlab_rails['backup_archive_permissions'] = 0644

gitlab_rails['backup_pg_schema'] = 'public'

## Git Data Directory's
git_data_dirs({
  'default' => {
    'path' => '/var/opt/gitlab/git-data'
  },
  # 'alternative' => {
  #   'path' => '/var/opt/gitlab/alternative-git-data'
  # },
})

### Gitaly settings
# gitlab_rails['gitaly_token'] = 'secret token'

## For storing GitLab application uploads, eg. LFS objects, build artifacts
##! Docs: https://docs.gitlab.com/ee/development/shared_files.html
gitlab_rails['shared_path'] = '/var/opt/gitlab/gitlab-rails/shared'

## GitLab Shell settings for GitLab
gitlab_rails['gitlab_shell_ssh_port'] = 22
gitlab_rails['gitlab_shell_git_timeout'] = 800

#### Change the initial default admin password and shared runner registration tokens.
gitlab_rails['initial_root_password'] = File.read('/run/secrets/gitlab_root_password')
# gitlab_rails['initial_shared_runners_registration_token'] = "token"

################################################################################
## Container Registry settings
##! Docs: https://docs.gitlab.com/ee/administration/container_registry.html
################################################################################

registry_external_url ENV['REGISTRY_EXTERNAL_SCHEME'] + "://" + ENV['REGISTRY_EXTERNAL_DOMAIN']

## Settings used by GitLab application
gitlab_rails['registry_enabled'] = true
# gitlab_rails['registry_host'] = ENV['REGISTRY_EXTERNAL_DOMAIN']
# gitlab_rails['registry_port'] = 443
gitlab_rails['registry_path'] = "/var/opt/gitlab/gitlab-rails/shared/registry"

gitlab_rails['registry_api_url'] = "http://localhost:5000"

## Settings used by Registry application
registry['enable'] = true
registry['dir'] = "/var/opt/gitlab/registry"
registry['registry_http_addr'] = "localhost:5000"
registry['log_directory'] = "/var/log/gitlab/registry"
registry['env_directory'] = "/opt/gitlab/etc/registry/env"
registry['log_level'] = "info"
registry['log_formatter'] = "text"
registry['health_storagedriver_enabled'] = true
registry['storage_delete_enabled'] = true
registry['validation_enabled'] = false
registry['autoredirect'] = false
registry['compatibility_schema1_enabled'] = false

################################################################################
## Error Reporting and Logging with Sentry
################################################################################
# gitlab_rails['sentry_enabled'] = false
# gitlab_rails['sentry_dsn'] = 'https://<key>@sentry.io/<project>'
# gitlab_rails['sentry_clientside_dsn'] = 'https://<key>@sentry.io/<project>'
# gitlab_rails['sentry_environment'] = 'production'

################################################################################
## GitLab NGINX
##! Docs: https://docs.gitlab.com/omnibus/settings/nginx.html
################################################################################

nginx['enable'] = true
nginx['client_max_body_size'] = '250m'
nginx['redirect_http_to_https'] = false

#! Docs: https://docs.gitlab.com/omnibus/settings/nginx.html#setting-the-nginx-listen-port
nginx['listen_port'] = ENV['EXTERNAL_PORT']

#! Docs: https://docs.gitlab.com/omnibus/settings/nginx.html#supporting-proxied-ssl
nginx['listen_https'] = false

nginx['redirect_http_to_https'] = false

################################################################################
## Users and groups accounts
##! Disable management of users and groups accounts.
##! **Set only if creating accounts manually**
##! Docs: https://docs.gitlab.com/omnibus/settings/configuration.html#disable-user-and-group-account-management
################################################################################

manage_accounts['enable'] = true

################################################################################
## GitLab Pages
##! Docs: https://docs.gitlab.com/ee/pages/administration.html
################################################################################

#! Define to enable GitLab Pages
pages_external_url ENV['PAGES_EXTERNAL_SCHEME'] + "://" + ENV['PAGES_EXTERNAL_DOMAIN']
gitlab_pages['enable'] = true

# #! Configure to expose GitLab Pages on external IP address, serving the HTTP
# gitlab_pages['external_http'] = []

# #! Configure to expose GitLab Pages on external IP address, serving the HTTPS
# gitlab_pages['external_https'] = []

#! Configure to enable health check endpoint on GitLab Pages
gitlab_pages['status_uri'] = "/@status"

gitlab_pages['log_format'] = "json"

##! Error Reporting and Logging with Sentry
# gitlab_pages['sentry_enabled'] = false
# gitlab_pages['sentry_dsn'] = 'https://<key>@sentry.io/<project>'
# gitlab_pages['sentry_environment'] = 'production'

gitlab_pages['dir'] = "/var/opt/gitlab/gitlab-pages"
gitlab_pages['log_directory'] = "/var/log/gitlab/gitlab-pages"

gitlab_pages['artifacts_server'] = true
gitlab_pages['artifacts_server_url'] = nil # Defaults to external_url + '/api/v4'
gitlab_pages['artifacts_server_timeout'] = 10

#! Environments that do not support bind-mounting should set this parameter to
#! true. This is incompatible with the artifacts server
gitlab_pages['inplace_chroot'] = true

#! Pages access control
gitlab_pages['access_control'] = true
gitlab_pages['gitlab_id'] = nil # Automatically generated if not present
gitlab_pages['gitlab_secret'] = nil # Generated if not present
gitlab_pages['auth_redirect_uri'] = nil # Defaults to projects subdomain of pages_external_url and + '/auth'
gitlab_pages['gitlab_server'] = nil # Defaults to external_url
gitlab_pages['internal_gitlab_server'] = nil # defaults to gitlab_server, can be changed to internal load balancer
gitlab_pages['auth_secret'] = nil # Generated if not present

################################################################################
## GitLab Pages NGINX
################################################################################

# Below you can find settings that are exclusive to "GitLab Pages NGINX"
pages_nginx['enable'] = true
pages_nginx['redirect_http_to_https'] = false
pages_nginx['listen_https'] = false
pages_nginx['listen_port'] = ENV['PAGES_EXTERNAL_PORT']

gitlab_rails['pages_path'] = "/var/opt/gitlab/gitlab-rails/shared/pages"

################################################################################
## GitLab CI
##! Docs: https://docs.gitlab.com/ee/ci/quick_start/README.html
################################################################################

gitlab_ci['gitlab_ci_all_broken_builds'] = true
gitlab_ci['gitlab_ci_add_pusher'] = true
gitlab_ci['builds_directory'] = '/var/opt/gitlab/gitlab-ci/builds'

################################################################################
## GitLab Mattermost
##! Docs: https://docs.gitlab.com/omnibus/gitlab-mattermost
################################################################################
mattermost_external_url ENV['MATTERMOST_EXTERNAL_SCHEME'] + "://" + ENV['MATTERMOST_EXTERNAL_DOMAIN']

mattermost['enable'] = true

################################################################################
## Mattermost NGINX
################################################################################

# Below you can find settings that are exclusive to "Mattermost NGINX"
mattermost_nginx['enable'] = false

mattermost_nginx['listen_port'] = ENV['MATTERMOST_EXTERNAL_PORT']

mattermost_nginx['redirect_http_to_https'] = false
mattermost_nginx['listen_https'] = false

################################################################################
## Registry NGINX
################################################################################

# Below you can find settings that are exclusive to "Registry NGINX"
registry_nginx['enable'] = true

registry_nginx['listen_port'] = ENV['REGISTRY_EXTERNAL_PORT']

registry_nginx['redirect_http_to_https'] = false
registry_nginx['listen_https'] = false

################################################################################
# Let's Encrypt integration
################################################################################
letsencrypt['enable'] = false

################################################################################
## Package repository (EE Only)
##! Docs: https://docs.gitlab.com/ee/administration/maven_packages.md
################################################################################

gitlab_rails['packages_enabled'] = true
gitlab_rails['packages_storage_path'] = "/var/opt/gitlab/packages"
